Repository cse110-sp24-group3/warmup-exercise, pull requests merged in 2024-04, with the labels that each got.

#6 PR: Front End Work Issue
  images/1.svg
  images/2.svg
  images/3.svg
  images/4.svg
  images/5.svg
  images/arrow.svg
  index.css
  index.html
Labels: PR

#14 [feat] enhanced some of the CSS styling
  index.css
  index.html
Labels: task

#16 [feat] Added hover effect on icons
  index.css
  index.html
Labels: PR

#23 Icon glow fixed
  index.css
Labels: PR

#24 [fix] - possibly fixed border overlay isseue when screen height is sm…
  index.css
Labels: PR

#25 Make slider more accessible through emoji icon clicking
  index.html
Labels: PR

#27 [test] added proof of functionality and documentation for tests
  tests/images/emotion1selected.png
  tests/images/emotion2selected.png
  tests/images/emotion3selected.png
  tests/images/emotion4selected.png
  tests/images/emotion5selected.png
  tests/images/galaxy20horizontal.png
  tests/images/galaxy20vertical.png
  tests/images/iPhone14horizontal.png
  tests/images/iPhone14vertical.png
  tests/test.md
Labels: documentation

#30 Testing submit
  tests/images/galaxy20horizontalfixed.png
  tests/images/iPhone14horizontalfixed.png
  tests/images/submitresponse.png
  tests/test.md
Labels: PR
